### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by crHARPER**
Refined Alternate firmware for the FG-100 using the ATmega328p.
Firmware CH-100 Ver. 1.00
* Improved button operation.
* Easier frequency setting with digit rollover, or wrap-around (9 to 0 and 0 to 9).
* Settings saved to EEPROM when Run Button is pressed.
* When Cursor Button is held down (>5 sec.), frequency resets to zero to simplify setup.
* Full 500KHz operation now implemented.

### CODE REVIEW

**Comment by crHARPER** [comment]
Great to see someone was working on better firmware for the FG-100.  Receive one a few weeks ago and couldn't believable the short comings of the firmware.  Found your repository via. HAck.io and saw what you had done and thought I'd see if I could polish it up a bit.  Not to add any complex features but to make it work the way one might expect.  New features are EEPROM as talked about and clearing the frequency value by holding down the cursor button.

**Comment by timsavage** [comment]
Awesome work, will give this a test in the next couple of days. I've done a quick run through and it all looks good.

Cheers

**Comment by crHARPER** [comment]
FYI, for programming, see Makefile "program", I put a 4.00MHz xtal 
(something I had on hand)  on Xtal1-Xtal2 so that I could switch the 
fuses back to internal OSC mode during programing.

Chris

**Comment by timsavage** [comment]
Yep, I saw that. I have an AVR development board with a crystal onboard but using the internal OSC is a good idea when programming. I'll need to do some tidying ups (normalise tabs/spaces) but it's all checking out.
The fix with the run/stop button is much better than my hack, don't know why I didn't think of that. Storing value to the EEPROM was something I had planned but had not implemented that feature on AVR previously. 
One thing I was still experimenting with was performing a frequency sweep, eg defining two frequencies to sweep between over a defined period. For designing and testing audio filters being able to sweep across frequencies would be useful.
There are still two unused pins on the micro that could be used to add additional functions (rotary encoder perhaps).
The only feature missing from the original firmware was a low battery voltage alert (via PIN 23), however, I didn't really see the point of this when it's being powered externally. Might have been for an alternative product. I have seen people convert their units to being battery powered and this feature would be useful in that case.

**Comment by crHARPER** [comment]
Ah,

I always use spaces for coding since tab widths can very but 'make' must 
have tabs.

Chris

**Pull request merged**
